### PR TITLE
Add Bruh.io

### PR DESCRIPTION
**Pull request by Samstiles**
Hey Matheus! Big fan :) Submitting my game for m28.studio. Let me know if you have any questions.

### CODE REVIEW

**Comment by Matheus28** [comment]
Hey, looks good to me. Could you make a 1200x800 image with some in-game sprites? Just so it's not just text.

Thank you.

**Comment by Matheus28** [comment]
Hi. Commenting again in case you didn't get a notification for the last reply.

**Comment by Samstiles** [comment]
@Matheus28 oh man I totally didn't get that notification! weird.

I'll get the asset for you tonight or tomorrow and update the PR!

**Comment by nobody5050** [comment]
@Samstiles you might want to get the image soon

**Pull request closed without merging**
