### PR TITLE
Added galax.io

### PR DESCRIPTION
**Pull request by NathanFlurry**
I'm not sure if this is the official way of adding games to this site (if there is one), but if so/you enjoy the game it would be much appreciated. Thanks!

### CODE REVIEW

**Comment by Matheus28** [comment]
Hi, looks good to me. It'll be live soon.

**Comment by Matheus28** [comment]
Actually, I just committed a cropped version of the image, can you add the game title on top of that?

**Comment by NathanFlurry** [comment]
Yeah, did I get the size wrong? I just copied the Strike Tactic's image size.

**Comment by Matheus28** [comment]
It was the border that looked kinda weird

**Pull request merged**
